### ISSUE TITLE
how to compare with other algorithm(monocle,TSCAN)？

### ISSUE THREAD

**Issue by handesome** [dpeerlab/Palantir#121]
Dear Palantir developers！！！
Palantir is a wonderful tool for trajectory analysis, please tell me how to compare palantir with other pseudotime trajectory?could you give some advice? Thanks!!!

**Comment by ManuSetty** [comment]
Thank you for reaching out. This question largely depends on the type of comparison you would like to make. The pseudo-time orderings from different approaches are in-large part quite similar between different algorithm with certain nuances. The major differences are from the way algorithms represent fate choices. Palantir treats this as a continuous process whereas the others do not. Are you trying to compare fate choice representations across the different methods?

**Comment by handesome** [comment]
Hi！Thank you for the reply!!YES,i'm  trying to compare fate choice representations across the different methods with some Evaluation metrics, such as Kendall's correlation, POS..  Thus, we could compared Palantir with the monocle2,TSCAN,Slingshot.could you please give some advice? Thanks again!!

**Comment by ManuSetty** [comment]
The fate choice representations are not directly comparable  because of how varied they are. The underlying philosophy of these methods are quite different and thus designing reliable distance metrics are hard. One could potentially try to identify branch points with palantir to compare to the other approaches but that does not necessarily provide a measure of performance for Palantir.

**Comment by handesome** [comment]
Thank you for the quick reply!!Now I know the reason!!
