### ISSUE TITLE
how to choose “start_cell”

### ISSUE THREAD

**Issue by Xyihang** [dpeerlab/Palantir#128]
start_cell = "Run5_164698952452459"
pr_res = palantir.core.run_palantir(
    ad, start_cell, num_waypoints=500, terminal_states=terminal_states
)

"Hello, I am wondering if there are any tools or principles that can assist us in automating or semi-automating the selection of a start_cell? How do we evaluate and choose between the final results of different start_cells, and are there any metrics that can reflect this?"

**Comment by katosh** [comment]
Hi @Xyihang,

There is indeed a way to use the diffusion components for a semi-automated selection of a start cell. The general idea is to find a component that peaks in the most stem-like cell type and then select the cell at this peak. This cell is thought of as being the most extrem stem-like cell in the dataset. E.g., if the most stem-like cell type of your dataset is `HSC` and the cell types are annotated in `ad.obs["celltype"]` then you can run:
```Python
start_cell = palantir.utils.early_cell(ad, "HSC", "celltype")
```

Pleas let me know if this helps.

**Comment by katosh** [comment]
Note that the above mentioned approach does not succeed if there is not diffusion component reaching its maximum or minimum in the specified cell type. This can be indicative of the cell type not containing a good start point or that too little diffusion components were computed. If you want to force Palantir to select a cell in the specified type, you can use the `fallback_seed ` argument. This enables the function to fall back to an algorithm that always selects a start cell that is however, not guaranteed to be a good start point. With the specified random seed it will select a random cell outside of the specified cell type and compute pseudo time starting from this cell to then select the "latest" cell within the specified cell type as the start cell. This is a good start cell if the specified cell type is an extreme point in the dataset and a random cell otherwise:
```Python
start_cell = palantir.utils.early_cell(ad, "HSC", "celltype", fallback_seed=236)
```
Please reopen this thread if this does not resolve the issue.
