### ISSUE TITLE
Diffusion Component Loadings

### ISSUE THREAD

**Issue by wbrett87** [dpeerlab/Palantir#142]
Hello!

I was wondering if there is any way to extract loadings for Palantir diffusion components to determine which genes contribute most to a specific component. Essentially like scanpy and seurat allow you to plot which genes contribute to specific principle components. ChatGPT is suggesting a workflow where I do a numpy dot product between the transposed adata.X and the diffusion components. No clue if that even makes any sense, but I tried and it crashes my computer (64gb RAM). 

Thanks!!

**Comment by katosh** [comment]
Hi @wbrett87, thank you for this interesting question.

Since the diffusion map is a non-linear mapping, the dot-product approach to infer loadings does not work here. Instead of computing eigenvectors of the covariance matrix, like in PCA, we compute eigenvectors of a diffusion based transition matrix. While this transition matrix is informed by the cell-to-cell similarity, which is in turn determined by the gene-expression levels, there is no other direct involvement of gene expression and hence no direct link between genes and diffusion map components. The advantage here is that phenotypic manifold can have any weird shape, e.g., form a spiral, and will be straitened out in diffusion map space. It is hard to call one gene more or less responsible for this diffusion map component beyond their variability in the dataset:
![image](https://github.com/dpeerlab/Palantir/assets/4857068/c853611a-f11e-418a-8af3-d5c18d72ed22)

**Comment by katosh** [comment]
No worries at all! You might find the [Gene-expression-trends section of the Palantir tutorial](https://palantir.readthedocs.io/en/latest/notebooks/Palantir_sample_notebook.html#Gene-expression-trends) interesting. It showcases how you could investigate how genes are changing as cells change, e.g., along a differentiation trajectory. While such a trajectory could be described by a single diffusion map component, it can also be a combination of multiple components.

You might also like the [gene-change-anaysis tutorial for Mellon](https://mellon.readthedocs.io/en/latest/notebooks/gene_change_analysis_tutorial.html). The score ranks each gene by the amount it changes when cells transition down a trajectory, inversely weighting by a cell-state density. The weighting ensures that the more rapid changes, that are inherently underrepresented in the dataset, are properly taken into account. Mellon is a dependency of Palantir, so if Palantir is running you should also be able to load Mellon. Refer to the [basic tutorial](https://mellon.readthedocs.io/en/latest/notebooks/basic_tutorial.html) for the required preprocessing.

Please let me know if you run into any issues! It always helps to see what people might get stuck with, so we can improve the software.
