### ISSUE TITLE
from_10x_HDF5

### ISSUE THREAD

**Issue by afrahshafquat** [dpeerlab/Palantir#27]
What does the genome argument require? I looked at the function and wasn't able to decipher what needed to be passed to the function? Any insight would be helpful

**Comment by afrahshafquat** [comment]
Also does this function convert an H5 object to a pandas dataframe instead of anndata object? If this is correct, does it make the analysis quite slow in comparison?

**Comment by afrahshafquat** [comment]
An extension of this could be a request to be able to manipulate scanpy objects directly through palantir once they have been created through sc.read_10x_h5 from scanpy. That functionality would be great!

**Comment by ManuSetty** [comment]
Thanks for pointing this out and apologies for the late response! 

We will work on fixing this since the functions are a bit of date. In the meantime, you can use Palantir through the scanpy interface and use the scanpy infrastructure for data input: https://icb-scanpy.readthedocs-hosted.com/en/stable/external/scanpy.external.tl.palantir.html

**Comment by ManuSetty** [comment]
Fixed in 72b94319b6e65319049ea76cdf0ef8d9cd0d9dd1
