### ISSUE TITLE
Stability of palantir results

### ISSUE THREAD

**Issue by dawe** [dpeerlab/Palantir#59]
Hi all, I'm using `palantir` on some data of mine, I've noticed that multiple runs with the same parameters give different result in entropy estimation, while pseudotime converges always to the same solution. This seems to be related to the estimation of branching trajectories, which varies across runs. 
Looking at branch probabilities in two examples, you may notice that some are conserved, while other appear to be merged/split as branch p_4 here
![branch2](https://user-images.githubusercontent.com/121868/112132342-c930b800-8bca-11eb-9566-90dc8de00b19.png)
which is split into branches p_0 and p_5 here
![branch1](https://user-images.githubusercontent.com/121868/112132428-e8c7e080-8bca-11eb-94f2-a16d46c7f86d.png)
Is there a way to enforce some type of convergence at this step?

**Comment by dawe** [comment]
Apparently increasing the waypoints (and knn) stabilizes the results, is this expected? I'm now set to `n_waypoints=adata.shape[0]//3`

**Comment by ManuSetty** [comment]
The waypoints are indeed randomly sampled and increasing the number of waypoints will indeed stabilize the results. Alternatively, setting the random seed using `np.random.seed` will ensure that waypoint samples are consistent.

**Comment by dawe** [comment]
Setting the random seed ensures results are always the same, but it doesn't grant their consistency, I may be in some local minima. I'll go with more waypoints at the cost of runtime (not much, <15m for 15k cells, <1h for ~40k cells)

**Comment by rahulnutron** [comment]
Dear Palantir team,
Thanks for the tool!
I am facing the same problem where branch probabilities are not stable. For me branch probabilities are important and ideally should be fixed in all runs for all cells using same parameters. I set the random seed, which doesn't seem to solve it. Do you recommend to increase the waypoints in this case?
Rahul

**Comment by ManuSetty** [comment]
Hello - you could increase the number of waypoints as a solution. Alternatively, you can save the set of waypoints from one of the runs and use it as input if you rerun Palantir. The waypoints are stored in `pr_res.waypoints` and the `num_waypoints` parameter can be set to a set of cells rather than the number.
